### ISSUE TITLE
StatusVariables prevent start of modules with different Qudi configuration [Bug] 

### ISSUE THREAD

**Issue by NicolasStaudenmaier** [Ulm-IQO/qudi-core#59]
### Version

Development

### What is affected by the bug?

Loading of a module does not work if features of the saved `StatusVariables` are not available with a different configuration of Qudi, though they may not be necessary for a working version of the module. 

### When does the bug occur?

The bug occurred to me when starting `pulsedmeasurement` of the IQO-modules. In a previous Qudi session I have used custom fit methods in pulsed measurements. Those fit methods were saved in the `StatusVariables` of the module. Switching to a different branch and starting pulsed measurements throws an error because the fit methods cannot be found. Starting of the module is impossible until the StatusVariable is deleted. 

### How do we replicate the issue?

- Create a new custom fit method in your branch
- Start Qudi and configure the fit (e.g. in the pulsed measurement module)
- Close Qudi
- Change to a different branch or delete the fit method 
- Start Qudi again and load the module where you have configured the fit

### Expected behavior

The module should load nonetheless, ignoring that minor saved features are not available. A warning message could be logged in that case.

**Comment by LukePiewalker** [comment]
I think I recall a discussion once about handling the Status Variables and sanitizing their status upon load. I think during this discussion the final state was that this should be handled on the module level itself.

However, defaulting Status Variables upon load if loading results in an error, might be something which could be done on the qudi-core level though, if there is no reason against it? If it is possible at all,?

**Comment by Neverhorst** [comment]
Hey @NicolasStaudenmaier @LukePiewalker ,
turns out the issue had nothing to do with `StatusVar`. Loading the fit configuration `StatusVar` into the fit model/container caused the error. This step is performed by the logic module owning the fit model.
Please have a look at PR #79 which should fix this issue by only logging a warning if the fit configuration can not be loaded and continue.
