### ISSUE TITLE
Broken link in getting_started

### ISSUE THREAD

**Issue by glennra** [Ulm-IQO/qudi-core#83]
https://github.com/Ulm-IQO/qudi-core/blob/eb2d4861141a6c72db894d91d07993f7ac9ec6a0/docs/getting_started.md?plain=1#L66C46-L66C46

This link is broken

**Comment by glennra** [comment]
Also it would be helpful to provide a link to the mentioned template module repository.

**Comment by timoML** [comment]
Thanks for the feedback. 
I updated the [getting_started](https://github.com/Ulm-IQO/qudi-core/blob/main/docs/getting_started.md).
Can you give some feedback if it's clearer now?

**Comment by glennra** [comment]
Yes it is much clearer now. Thank you.
There is still this bug though:
https://github.com/Ulm-IQO/qudi-core/blob/49d590caa65c92424dbca4caf97f9d528e6c391a/docs/getting_started.md?plain=1#L44C12-L44C12
says to load 'default.cfg' as mentioned in the installation guide but I couldn't find it mentioned in https://github.com/Ulm-IQO/qudi-core/blob/main/docs/setup/installation.md

**Comment by timoML** [comment]
The reason for this is that [default.cfg](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/src/qudi/default.cfg) is part of  qudi-iqo-modules now and the referenced [installation guide](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/docs/installation_guide.md) is the one from qudi-iqo-modules. Do you have a suggestion on how to make this point even clearer?

**Comment by Neverhorst** [comment]
Just to make this perfectly clear:
`qudi-core` does not contain any measurement toolchains. It just provides the framework as well as some useful tooling and libraries to develop addon packages. One such package (aimed at colorcenter research) is `qudi-iqo-modules`. 

So if you want to start any GUIs or dummy measurements, the corresponding example configuration is always provided by the respective repository where these toolchains are coming from. In the case of `qudi-iqo-modules` this would be `default.cfg` located at `<repository_root>/src/qudi/default.cfg`.

The idea behind this separation is, that you do not have to install Gigabytes of useless toolchains and Python packages if you just want to implement your own measurement library. It simplifies package management tremendously.

**Comment by glennra** [comment]
> The reason for this is that [default.cfg](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/src/qudi/default.cfg) is part of qudi-iqo-modules now and the referenced [installation guide](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/docs/installation_guide.md) is the one from qudi-iqo-modules. Do you have a suggestion on how to make this point even clearer?

Maybe a link like the one in this comment would suffice and/or mention explicitly that the installation guide being referred to is the one for qudi-igo-modules.

**Comment by glennra** [comment]
The reason for my confusion is that a document called "installation guide" is named here https://github.com/Ulm-IQO/qudi-core/blob/a4db9b0e6f637ac6963d67e31afd813563ab1a5c/docs/getting_started.md?plain=1#L23 but that is not the installation guide referred to here https://github.com/Ulm-IQO/qudi-core/blob/a4db9b0e6f637ac6963d67e31afd813563ab1a5c/docs/getting_started.md?plain=1#L48

**Comment by timoML** [comment]
I clearified this part in the docs again. 
Any help on our documentation is always highly appreciated. So please feel free to post again with suggestions to improve.

**Comment by timoML** [comment]
Closed as no more issues with getting_started.md were reported.
